// SAT-style math question bank.
// type: "mc" (multiple choice, options A-D) or "grid" (numeric free-response, like SAT grid-ins)
// timeLimit is in seconds. Answers for "grid" are matched as trimmed strings (numeric).

const QUESTIONS = [
  {
    id: "alg-1",
    category: "Algebra",
    type: "mc",
    prompt: "If 3x - 7 = 2x + 5, what is the value of x?",
    options: ["-12", "2", "12", "5"],
    answer: 2,
    timeLimit: 90,
  },
  {
    id: "alg-2",
    category: "Algebra",
    type: "mc",
    prompt: "A line passes through the points (2, 5) and (4, 11). What is the slope of the line?",
    options: ["2", "3", "6", "1/3"],
    answer: 1,
    timeLimit: 90,
  },
  {
    id: "alg-3",
    category: "Algebra",
    type: "grid",
    prompt: "If 2(x + 3) = 4x - 2, what is the value of x?",
    answer: "4",
    timeLimit: 90,
  },
  {
    id: "alg-4",
    category: "Algebra",
    type: "mc",
    prompt: "The function f(x) = 4x - 9 is graphed in the xy-plane. What is the x-intercept of the graph?",
    options: ["(0, -9)", "(9/4, 0)", "(-9/4, 0)", "(4, 0)"],
    answer: 1,
    timeLimit: 90,
  },
  {
    id: "adv-1",
    category: "Advanced Math",
    type: "mc",
    prompt: "Which of the following is equivalent to (x + 4)(x - 6)?",
    options: [
      "x^2 - 2x - 24",
      "x^2 + 2x - 24",
      "x^2 - 2x + 24",
      "x^2 - 24",
    ],
    answer: 0,
    timeLimit: 90,
  },
  {
    id: "adv-2",
    category: "Advanced Math",
    type: "grid",
    prompt: "If x^2 - 10x + 25 = 0, what is the value of x?",
    answer: "5",
    timeLimit: 90,
  },
  {
    id: "adv-3",
    category: "Advanced Math",
    type: "mc",
    prompt: "For the exponential function g, g(0) = 3 and g(x) = g(x-1) * 2 for all integers x > 0. What is g(4)?",
    options: ["12", "24", "48", "96"],
    answer: 2,
    timeLimit: 105,
  },
  {
    id: "adv-4",
    category: "Advanced Math",
    type: "mc",
    prompt: "If f(x) = 2x^2 - 3x + 1, what is f(-2)?",
    options: ["3", "9", "15", "-15"],
    answer: 2,
    timeLimit: 90,
  },
  {
    id: "geo-1",
    category: "Geometry & Trig",
    type: "mc",
    prompt: "A circle has a circumference of 18π. What is the radius of the circle?",
    options: ["3", "6", "9", "18"],
    answer: 1,
    timeLimit: 90,
  },
  {
    id: "geo-2",
    category: "Geometry & Trig",
    type: "grid",
    prompt: "A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?",
    answer: "10",
    timeLimit: 90,
  },
  {
    id: "geo-3",
    category: "Geometry & Trig",
    type: "mc",
    prompt: "In a right triangle, one angle measures 30 degrees. What is the measure, in degrees, of the other acute angle?",
    options: ["45", "50", "60", "70"],
    answer: 2,
    timeLimit: 75,
  },
  {
    id: "geo-4",
    category: "Geometry & Trig",
    type: "mc",
    prompt: "The volume of a rectangular box is 240 cubic inches. If the length is 8 inches and the width is 6 inches, what is the height, in inches?",
    options: ["4", "5", "6", "8"],
    answer: 1,
    timeLimit: 90,
  },
  {
    id: "data-1",
    category: "Problem Solving & Data Analysis",
    type: "mc",
    prompt: "A store marks up the price of an item by 25% and then offers a 20% discount on the marked-up price. What is the final price as a percent of the original price?",
    options: ["90%", "95%", "100%", "105%"],
    answer: 2,
    timeLimit: 105,
  },
  {
    id: "data-2",
    category: "Problem Solving & Data Analysis",
    type: "grid",
    prompt: "The average (arithmetic mean) of 4 numbers is 15. If three of the numbers are 10, 12, and 18, what is the fourth number?",
    answer: "20",
    timeLimit: 90,
  },
  {
    id: "data-3",
    category: "Problem Solving & Data Analysis",
    type: "mc",
    prompt: "In a survey of 200 students, 60% said they prefer studying in the morning. How many students prefer studying in the morning?",
    options: ["60", "120", "140", "160"],
    answer: 1,
    timeLimit: 75,
  },
  {
    id: "data-4",
    category: "Problem Solving & Data Analysis",
    type: "mc",
    prompt: "A car travels 270 miles using 9 gallons of gas. At this rate, how many gallons of gas would the car need to travel 450 miles?",
    options: ["12", "13.5", "15", "18"],
    answer: 2,
    timeLimit: 90,
  },
  {
    id: "alg-5",
    category: "Algebra",
    type: "mc",
    prompt: "If 5x + 2y = 20 and x = 2, what is the value of y?",
    options: ["5", "8", "10", "12"],
    answer: 0,
    timeLimit: 75,
  },
  {
    id: "adv-5",
    category: "Advanced Math",
    type: "grid",
    prompt: "If (x - 3)^2 = 49 and x > 0, what is the value of x?",
    answer: "10",
    timeLimit: 105,
  },
  {
    id: "geo-5",
    category: "Geometry & Trig",
    type: "mc",
    prompt: "A square has an area of 64 square centimeters. What is the perimeter of the square, in centimeters?",
    options: ["16", "24", "32", "64"],
    answer: 2,
    timeLimit: 75,
  },
  {
    id: "data-5",
    category: "Problem Solving & Data Analysis",
    type: "grid",
    prompt: "A rectangle's length is 3 times its width. If the perimeter is 64, what is the width?",
    answer: "8",
    timeLimit: 105,
  },
];
